name: "Bump chainguard digest"
description: "Bumps digests of chainguard images. For nightly jobs."

inputs:
  image_name:
    required: true
    description: "Name of the image to check for (e.g. nginx)."
  file_path:
    required: true
    description: "Path to the file where the image is located (e.g frontend/Dockerfile)."
  github_token:
    required: true
    description: "GitHub token for pushing changes."

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Construct full image name for ${{ inputs.image_name }}
      shell: bash
      run: |
        set -ex
        echo "FULL_IMAGE_NAME=cgr.dev/chainguard/${{ inputs.image_name }}:latest" >> $GITHUB_ENV
    - name: Pull latest image
      shell: bash
      run: |
        set -ex
        docker pull $FULL_IMAGE_NAME
    - name: Get newest digest
      shell: bash
      run: |
        set -ex
        echo "IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $FULL_IMAGE_NAME | cut -d'@' -f2)" >> $GITHUB_ENV
    - name: Update digests in the repository
      shell: bash
      run: |
        set -ex
        sed -i -E "s|(${{ inputs.image_name }}@)[^ ]*|\1$IMAGE_DIGEST|g" ${{ inputs.file_path }}
    - name: Commit and push changes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        set -ex
        git config user.name "${{ github.workflow }}"
        # This email identifies the commit as GitHub Actions - see https://github.com/orgs/community/discussions/26560
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ${{ inputs.file_path }}
        git diff-index --cached --quiet HEAD ||
          git commit -m "Bump chainguard image for ${{ inputs.image_name }}" -m "[skip ci]" &&
          git push origin main
